#Minecraft server properties
#Mon Jan 27 12:35:38 UTC 2025
view-distance=10
max-build-height=256
server-ip=
level-seed=
gamemode=1
enable-command-block=true
allow-nether=true
server-port=25565
enable-rcon=false
enable-query=false
op-permission-level=4
server-name=Unknown Server
generator-settings=
resource-pack=
level-name=world
player-idle-timeout=0
motd=A Minecraft Server
announce-player-achievements=true
debug=false
force-gamemode=false
hardcore=false
white-list=false
broadcast-console-to-ops=true
pvp=true
spawn-npcs=false
generate-structures=false
spawn-animals=false
snooper-enabled=true
difficulty=1
network-compression-threshold=256
level-type=FLAT
spawn-monsters=false
max-players=100
use-native-transport=false
spawn-protection=16
online-mode=false
allow-flight=false
max-world-size=29999984
resource-pack-hash=
